#!/usr/bin/env bash

DIR=/sys/class/power_supply


CONSERVE="/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode"

if [ ! -f "$CONSERVE" ] ; then
	echo "Could not find conservation mode file."
	exit 1
fi

get_charge_threshold() {
	if [ -f "$CONSERVE" ] && [ "$(cat "$CONSERVE")" -eq 1 ]; then
		echo 80
	else
		echo 100
	fi
}

# arg1: BAT0 or BAT1 that is charging
show_est() {
  power=$(cat "$DIR/$1/power_now")
  if [ "$power" -eq 0 ] ; then
	return
  fi
  bat0_ef=$(cat "$DIR/BAT0/energy_full")
  bat0_et=$(get_charge_threshold)
  final=$(("($bat0_ef * $bat0_et) / 100"))
  charge0=$(cat "$DIR/BAT0/energy_now")
  ttf=$(("60 * ($final - $charge0) / $power"))
  hours=$(("$ttf / 60"))
  mins=$(printf "%02d" $(("$ttf % 60")))
  echo "$hours":"$mins"
}

# arg1: BAT0 or BAT1 that is discharging
report_watts() {
  # Take a reading in microwatts, then take the integer half
  # and the decimal half and concatenate them using a period.
  power=$(cat "$DIR/$1/power_now")
  if [ ! "$power" = "" ]
  then 
    trunc=$(("$power / 1000000"))
    dec=$(("$power % 1000000 / 100000"))
    echo "$trunc.$dec"
  fi
}

bat0_status=$(cat "$DIR/BAT0/status")

if [ "$bat0_status" = "Discharging" ]
then report_watts BAT0
elif [ "$bat0_status" = "Charging" ]
then show_est BAT0
fi

